// Static metadata for the 100 NASDAQ-100 constituents.
// Fields: { name, sector, industry, hq, color, desc }
// `color` is the brand's signature hex — used for the monogram fallback when a
// PNG logo isn't on disk, and as a tint accent in the row.
//
// Hand-curated from public sources (Wikipedia, SEC filings, company press kits).
// Kept intentionally one-sentence so the row stays scannable.
export const COMPANIES = {
  AAPL: { name:'Apple Inc.',                   sector:'Tech',         industry:'Consumer Electronics',  hq:'Cupertino, CA',     color:'#000000', desc:'Designs the iPhone, Mac, Watch, and the services ecosystem around them.' },
  MSFT: { name:'Microsoft',                    sector:'Tech',         industry:'Software · Cloud',      hq:'Redmond, WA',       color:'#00BCF2', desc:'Windows, Office, Azure, GitHub, Xbox — and the largest enterprise software footprint on Earth.' },
  NVDA: { name:'NVIDIA',                       sector:'Tech',         industry:'Semiconductors',        hq:'Santa Clara, CA',   color:'#76B900', desc:'GPUs that power gaming, datacenter AI training, and the entire LLM boom.' },
  AMZN: { name:'Amazon',                       sector:'Consumer',     industry:'E-commerce · Cloud',    hq:'Seattle, WA',       color:'#FF9900', desc:'World\'s largest online retailer; AWS is the largest public cloud.' },
  META: { name:'Meta Platforms',               sector:'Communications',industry:'Social Media',         hq:'Menlo Park, CA',    color:'#1877F2', desc:'Owns Facebook, Instagram, WhatsApp, and the Reality Labs metaverse bet.' },
  GOOGL:{ name:'Alphabet (Class A)',           sector:'Communications',industry:'Internet · Ads',       hq:'Mountain View, CA', color:'#4285F4', desc:'Parent of Google Search, YouTube, Android, Cloud, and Waymo.' },
  GOOG: { name:'Alphabet (Class C)',           sector:'Communications',industry:'Internet · Ads',       hq:'Mountain View, CA', color:'#4285F4', desc:'Same Alphabet, non-voting share class.' },
  AVGO: { name:'Broadcom',                     sector:'Tech',         industry:'Semiconductors',        hq:'Palo Alto, CA',     color:'#CC092F', desc:'Networking and wireless chips plus enterprise software (VMware).' },
  TSLA: { name:'Tesla',                        sector:'Consumer',     industry:'Auto · Energy',         hq:'Austin, TX',        color:'#CC0000', desc:'Electric vehicles, batteries, solar, and Full Self-Driving software.' },
  COST: { name:'Costco Wholesale',             sector:'Consumer',     industry:'Membership Retail',     hq:'Issaquah, WA',      color:'#005DAA', desc:'Membership-only big-box retailer famously generous with hot dogs.' },
  NFLX: { name:'Netflix',                      sector:'Communications',industry:'Streaming Media',      hq:'Los Gatos, CA',     color:'#E50914', desc:'Subscription streaming pioneer; ~280M global members.' },
  TMUS: { name:'T-Mobile US',                  sector:'Communications',industry:'Wireless Carrier',     hq:'Bellevue, WA',      color:'#E20074', desc:'Third-largest US carrier; the un-carrier rebrand stuck.' },
  ASML: { name:'ASML Holding',                 sector:'Tech',         industry:'Semi Equipment',        hq:'Veldhoven, NL',     color:'#0F50A1', desc:'Sole supplier of EUV lithography machines — the chip industry runs on these.' },
  AZN:  { name:'AstraZeneca',                  sector:'Healthcare',   industry:'Pharma',                hq:'Cambridge, UK',     color:'#830051', desc:'Anglo-Swedish drugmaker (oncology, respiratory, COVID vaccine).' },
  CSCO: { name:'Cisco Systems',                sector:'Tech',         industry:'Networking',            hq:'San Jose, CA',      color:'#1BA0D7', desc:'Routers, switches, and the security stack that the enterprise internet runs on.' },
  AMD:  { name:'Advanced Micro Devices',       sector:'Tech',         industry:'Semiconductors',        hq:'Santa Clara, CA',   color:'#ED1C24', desc:'CPUs (Ryzen, EPYC) and GPUs (Radeon, Instinct) — Intel\'s most credible rival.' },
  PEP:  { name:'PepsiCo',                      sector:'Consumer',     industry:'Beverages · Snacks',    hq:'Purchase, NY',      color:'#004B93', desc:'Pepsi, Mountain Dew, Gatorade, Lay\'s, Doritos, Quaker Oats.' },
  LIN:  { name:'Linde',                        sector:'Materials',    industry:'Industrial Gases',      hq:'Woking, UK',        color:'#005CB9', desc:'World\'s largest industrial-gas company — oxygen, nitrogen, hydrogen at scale.' },
  ADBE: { name:'Adobe',                        sector:'Tech',         industry:'Creative Software',     hq:'San Jose, CA',      color:'#FA0F00', desc:'Photoshop, Illustrator, Premiere, Acrobat — the creative-pro toolkit.' },
  INTU: { name:'Intuit',                       sector:'Tech',         industry:'Fintech Software',      hq:'Mountain View, CA', color:'#236CFF', desc:'TurboTax, QuickBooks, Credit Karma, Mailchimp.' },
  TXN:  { name:'Texas Instruments',            sector:'Tech',         industry:'Semiconductors',        hq:'Dallas, TX',        color:'#CC0000', desc:'Analog and embedded chips — the boring-but-essential silicon in everything.' },
  ARM:  { name:'Arm Holdings',                 sector:'Tech',         industry:'Chip IP',               hq:'Cambridge, UK',     color:'#0091BD', desc:'Designs the CPU architectures that power virtually every smartphone.' },
  QCOM: { name:'Qualcomm',                     sector:'Tech',         industry:'Semiconductors',        hq:'San Diego, CA',     color:'#3253DC', desc:'Snapdragon SoCs and the modem patents behind every cellular device.' },
  ISRG: { name:'Intuitive Surgical',           sector:'Healthcare',   industry:'Med Devices',           hq:'Sunnyvale, CA',     color:'#1F2A44', desc:'Maker of the da Vinci robotic surgery system.' },
  AMGN: { name:'Amgen',                        sector:'Healthcare',   industry:'Biotech',               hq:'Thousand Oaks, CA', color:'#0033A0', desc:'Biotech pioneer — Enbrel, Repatha, Prolia, Otezla.' },
  PDD:  { name:'PDD Holdings',                 sector:'Consumer',     industry:'E-commerce',            hq:'Dublin, Ireland',   color:'#E02E24', desc:'Parent of Pinduoduo (China) and the explosive-growth Temu app.' },
  BKNG: { name:'Booking Holdings',             sector:'Consumer',     industry:'Online Travel',         hq:'Norwalk, CT',       color:'#003580', desc:'Booking.com, Priceline, Kayak, OpenTable, Agoda — most of online travel.' },
  AMAT: { name:'Applied Materials',            sector:'Tech',         industry:'Semi Equipment',        hq:'Santa Clara, CA',   color:'#0066B2', desc:'Manufacturing equipment for semiconductor fabs.' },
  PANW: { name:'Palo Alto Networks',           sector:'Tech',         industry:'Cybersecurity',         hq:'Santa Clara, CA',   color:'#FA582D', desc:'Next-gen firewalls and the platform consolidating enterprise security.' },
  HON:  { name:'Honeywell',                    sector:'Industrials',  industry:'Diversified',           hq:'Charlotte, NC',     color:'#E2231A', desc:'Aerospace, building tech, performance materials, automation.' },
  CMCSA:{ name:'Comcast',                      sector:'Communications',industry:'Cable · Media',        hq:'Philadelphia, PA',  color:'#000000', desc:'Xfinity broadband, NBCUniversal, Sky, and Peacock.' },
  GILD: { name:'Gilead Sciences',              sector:'Healthcare',   industry:'Biotech',               hq:'Foster City, CA',   color:'#A4123F', desc:'Antivirals — HIV, hepatitis C, COVID (Veklury).' },
  ADP:  { name:'Automatic Data Processing',    sector:'Tech',         industry:'HR · Payroll',          hq:'Roseland, NJ',      color:'#D71921', desc:'Runs payroll for one in six American workers.' },
  VRTX: { name:'Vertex Pharmaceuticals',       sector:'Healthcare',   industry:'Biotech',               hq:'Boston, MA',        color:'#005EB8', desc:'Cystic fibrosis franchise (Trikafta) and gene-edited sickle cell therapy.' },
  MELI: { name:'MercadoLibre',                 sector:'Consumer',     industry:'E-commerce · Fintech',  hq:'Buenos Aires, AR',  color:'#FFE600', desc:'Latin America\'s dominant marketplace + Mercado Pago payments.' },
  LRCX: { name:'Lam Research',                 sector:'Tech',         industry:'Semi Equipment',        hq:'Fremont, CA',       color:'#3A6BA5', desc:'Etch and deposition tools for chip manufacturing.' },
  MU:   { name:'Micron Technology',            sector:'Tech',         industry:'Memory Chips',          hq:'Boise, ID',         color:'#000000', desc:'DRAM and NAND flash — one of three remaining DRAM makers globally.' },
  ADI:  { name:'Analog Devices',               sector:'Tech',         industry:'Semiconductors',        hq:'Wilmington, MA',    color:'#012168', desc:'High-performance analog, mixed-signal, and DSP chips.' },
  KLAC: { name:'KLA Corporation',              sector:'Tech',         industry:'Semi Equipment',        hq:'Milpitas, CA',      color:'#005DA9', desc:'Process control and yield management for semiconductor fabs.' },
  APP:  { name:'AppLovin',                     sector:'Tech',         industry:'Mobile Ad Tech',        hq:'Palo Alto, CA',     color:'#000000', desc:'Mobile-game ad network (AXON ML platform); explosive 2024-2025 run.' },
  SBUX: { name:'Starbucks',                    sector:'Consumer',     industry:'Restaurants',           hq:'Seattle, WA',       color:'#006241', desc:'~38,000 stores worldwide; the rewards app is also a bank.' },
  INTC: { name:'Intel',                        sector:'Tech',         industry:'Semiconductors',        hq:'Santa Clara, CA',   color:'#0071C5', desc:'CPUs and now (again) chip foundry; mid-turnaround under Gelsinger.' },
  CRWD: { name:'CrowdStrike',                  sector:'Tech',         industry:'Cybersecurity',         hq:'Austin, TX',        color:'#FF0000', desc:'Cloud-native endpoint protection (Falcon platform).' },
  CEG:  { name:'Constellation Energy',         sector:'Utilities',    industry:'Nuclear · Power',       hq:'Baltimore, MD',     color:'#00263E', desc:'Largest US nuclear-power producer; spun out of Exelon in 2022.' },
  MDLZ: { name:'Mondelez International',       sector:'Consumer',     industry:'Snacks',                hq:'Chicago, IL',       color:'#7C4F9F', desc:'Oreo, Cadbury, Toblerone, Ritz, Trident — most of the snack aisle.' },
  CTAS: { name:'Cintas',                       sector:'Industrials',  industry:'Uniform Services',      hq:'Cincinnati, OH',    color:'#003DA5', desc:'Uniform rental, facility services, first aid — the company you don\'t notice running everything.' },
  PYPL: { name:'PayPal',                       sector:'Financials',   industry:'Payments',              hq:'San Jose, CA',      color:'#003087', desc:'PayPal, Venmo, Braintree, Xoom — digital payments.' },
  MAR:  { name:'Marriott International',       sector:'Consumer',     industry:'Hotels',                hq:'Bethesda, MD',      color:'#A0282D', desc:'World\'s largest hotel company — 30 brands, 8,500+ properties.' },
  PLTR: { name:'Palantir Technologies',        sector:'Tech',         industry:'Data Software',         hq:'Denver, CO',        color:'#101113', desc:'Gotham (gov) and Foundry (commercial) data-integration platforms; AIP for LLMs.' },
  SNPS: { name:'Synopsys',                     sector:'Tech',         industry:'EDA Software',          hq:'Sunnyvale, CA',     color:'#1F4DA1', desc:'Electronic design automation tools — every modern chip is built on these.' },
  MRVL: { name:'Marvell Technology',           sector:'Tech',         industry:'Semiconductors',        hq:'Wilmington, DE',    color:'#0066B3', desc:'Custom silicon for cloud, 5G, automotive, and storage.' },
  CDNS: { name:'Cadence Design Systems',       sector:'Tech',         industry:'EDA Software',          hq:'San Jose, CA',      color:'#13284B', desc:'Cadence is the other half of the EDA duopoly with Synopsys.' },
  REGN: { name:'Regeneron Pharmaceuticals',    sector:'Healthcare',   industry:'Biotech',               hq:'Tarrytown, NY',     color:'#005EB8', desc:'Eylea, Dupixent, and the COVID antibody cocktail; deep antibody R&D.' },
  FTNT: { name:'Fortinet',                     sector:'Tech',         industry:'Cybersecurity',         hq:'Sunnyvale, CA',     color:'#EE3124', desc:'FortiGate firewalls and the Security Fabric platform.' },
  ORLY: { name:'O\'Reilly Automotive',         sector:'Consumer',     industry:'Auto Parts Retail',     hq:'Springfield, MO',   color:'#00563F', desc:'Auto parts retail chain (~6,000 stores in the US).' },
  ABNB: { name:'Airbnb',                       sector:'Consumer',     industry:'Online Travel',         hq:'San Francisco, CA', color:'#FF5A5F', desc:'Marketplace for short-term rentals and experiences.' },
  CSX:  { name:'CSX Corporation',              sector:'Industrials',  industry:'Class I Rail',          hq:'Jacksonville, FL',  color:'#003F87', desc:'Eastern US freight railroad — 21,000 miles of track.' },
  TRI:  { name:'Thomson Reuters',              sector:'Industrials',  industry:'Info Services',         hq:'Toronto, Canada',   color:'#FA6400', desc:'Legal (Westlaw), tax, news, and the Reuters newswire.' },
  WDAY: { name:'Workday',                      sector:'Tech',         industry:'HR · Finance Cloud',    hq:'Pleasanton, CA',    color:'#F38B00', desc:'Cloud HCM and finance software; the modern Oracle/SAP rival.' },
  ROP:  { name:'Roper Technologies',           sector:'Industrials',  industry:'Diversified Software',  hq:'Sarasota, FL',      color:'#212F60', desc:'Holding company of vertical-niche software businesses.' },
  NXPI: { name:'NXP Semiconductors',           sector:'Tech',         industry:'Semiconductors',        hq:'Eindhoven, NL',     color:'#000000', desc:'Automotive, industrial, IoT, and contactless-payment chips.' },
  AEP:  { name:'American Electric Power',      sector:'Utilities',    industry:'Electric Utility',      hq:'Columbus, OH',      color:'#E97600', desc:'One of the largest US electric utilities — 5.5M customers across 11 states.' },
  CHTR: { name:'Charter Communications',       sector:'Communications',industry:'Cable · Internet',     hq:'Stamford, CT',      color:'#0099D8', desc:'Spectrum-branded cable and broadband — second-largest US ISP.' },
  PCAR: { name:'PACCAR',                       sector:'Industrials',  industry:'Trucks',                hq:'Bellevue, WA',      color:'#2C5F2D', desc:'Kenworth, Peterbilt, DAF — heavy-duty truck manufacturer.' },
  MNST: { name:'Monster Beverage',             sector:'Consumer',     industry:'Beverages',             hq:'Corona, CA',        color:'#00FF00', desc:'Monster Energy and the energy-drinks portfolio.' },
  PAYX: { name:'Paychex',                      sector:'Tech',         industry:'HR · Payroll',          hq:'Rochester, NY',     color:'#005A9C', desc:'Payroll, HR, and benefits services for SMBs.' },
  ROST: { name:'Ross Stores',                  sector:'Consumer',     industry:'Off-price Retail',      hq:'Dublin, CA',        color:'#0095DA', desc:'Off-price apparel and home goods chain (Ross Dress for Less).' },
  ADSK: { name:'Autodesk',                     sector:'Tech',         industry:'Design Software',       hq:'San Francisco, CA', color:'#000000', desc:'AutoCAD, Revit, Maya, Fusion 360 — engineering and design tools.' },
  KDP:  { name:'Keurig Dr Pepper',             sector:'Consumer',     industry:'Beverages',             hq:'Burlington, MA',    color:'#9C162C', desc:'Single-serve coffee (Keurig) and a flavored-soda portfolio.' },
  FAST: { name:'Fastenal',                     sector:'Industrials',  industry:'Industrial Distrib.',   hq:'Winona, MN',        color:'#003B71', desc:'Industrial supply distributor — fasteners, safety, MRO.' },
  DASH: { name:'DoorDash',                     sector:'Consumer',     industry:'Food Delivery',         hq:'San Francisco, CA', color:'#FF3008', desc:'Largest US food-delivery marketplace; expanding into grocery and convenience.' },
  TEAM: { name:'Atlassian',                    sector:'Tech',         industry:'Dev Tools',             hq:'Sydney, Australia', color:'#0052CC', desc:'Jira, Confluence, Bitbucket, Trello — software-team collaboration.' },
  ODFL: { name:'Old Dominion Freight Line',    sector:'Industrials',  industry:'LTL Trucking',          hq:'Thomasville, NC',   color:'#003F7F', desc:'Less-than-truckload trucking with industry-leading service metrics.' },
  CPRT: { name:'Copart',                       sector:'Industrials',  industry:'Vehicle Auctions',      hq:'Dallas, TX',        color:'#0072BC', desc:'Online auctions for salvage and used vehicles; ~$15B GMV.' },
  BKR:  { name:'Baker Hughes',                 sector:'Energy',       industry:'Oilfield Services',     hq:'Houston, TX',       color:'#00ADBB', desc:'Oilfield equipment and services + industrial energy tech.' },
  KHC:  { name:'Kraft Heinz',                  sector:'Consumer',     industry:'Packaged Foods',        hq:'Pittsburgh, PA',    color:'#D71921', desc:'Heinz, Kraft, Philadelphia, Oscar Mayer, Jell-O — pantry staples.' },
  DDOG: { name:'Datadog',                      sector:'Tech',         industry:'Observability',         hq:'New York, NY',      color:'#632CA6', desc:'Cloud monitoring, logs, APM, and security observability platform.' },
  EA:   { name:'Electronic Arts',              sector:'Communications',industry:'Video Games',          hq:'Redwood City, CA',  color:'#FF4747', desc:'EA Sports (FC, Madden, NHL), Apex Legends, The Sims, Battlefield.' },
  GEHC: { name:'GE HealthCare',                sector:'Healthcare',   industry:'Med Imaging',           hq:'Chicago, IL',       color:'#005EB8', desc:'MRI, CT, ultrasound, and patient monitoring equipment; 2023 GE spinoff.' },
  EXC:  { name:'Exelon',                       sector:'Utilities',    industry:'Electric Utility',      hq:'Chicago, IL',       color:'#0094D9', desc:'Largest US regulated utility holding company by customer count.' },
  XEL:  { name:'Xcel Energy',                  sector:'Utilities',    industry:'Electric & Gas',        hq:'Minneapolis, MN',   color:'#0083C1', desc:'Regulated electric and gas utility across eight Midwestern/Western states.' },
  CTSH: { name:'Cognizant Technology Solutions',sector:'Tech',        industry:'IT Services',           hq:'Teaneck, NJ',       color:'#1A4480', desc:'Global IT services and consulting; major offshore delivery footprint.' },
  VRSK: { name:'Verisk Analytics',             sector:'Industrials',  industry:'Insurance Analytics',   hq:'Jersey City, NJ',   color:'#0032A0', desc:'Risk-assessment data and analytics for the insurance industry.' },
  LULU: { name:'Lululemon Athletica',          sector:'Consumer',     industry:'Athletic Apparel',      hq:'Vancouver, Canada', color:'#A20030', desc:'Yoga-rooted athletic apparel; expanding into men\'s and footwear.' },
  CCEP: { name:'Coca-Cola Europacific Partners',sector:'Consumer',    industry:'Beverages Bottler',     hq:'Uxbridge, UK',      color:'#F40009', desc:'Coca-Cola bottler covering Europe, Australia, and the Pacific.' },
  IDXX: { name:'IDEXX Laboratories',           sector:'Healthcare',   industry:'Vet Diagnostics',       hq:'Westbrook, ME',     color:'#005DAB', desc:'Diagnostics for veterinary practice — companion animals and livestock.' },
  ZS:   { name:'Zscaler',                      sector:'Tech',         industry:'Cybersecurity',         hq:'San Jose, CA',      color:'#00B5E2', desc:'Zero-trust cloud security platform (ZIA, ZPA).' },
  ANSS: { name:'Ansys',                        sector:'Tech',         industry:'Simulation Software',   hq:'Canonsburg, PA',    color:'#FFB71B', desc:'Multiphysics simulation — being acquired by Synopsys.' },
  TTWO: { name:'Take-Two Interactive',         sector:'Communications',industry:'Video Games',          hq:'New York, NY',      color:'#F00000', desc:'Rockstar Games (GTA, Red Dead) and 2K (NBA 2K, Borderlands).' },
  AXON: { name:'Axon Enterprise',              sector:'Industrials',  industry:'Public Safety Tech',    hq:'Scottsdale, AZ',    color:'#FFD200', desc:'TASERs, body cameras, and Evidence.com cloud platform.' },
  CSGP: { name:'CoStar Group',                 sector:'Industrials',  industry:'Real Estate Data',      hq:'Washington, DC',    color:'#003594', desc:'Commercial real estate data; owns Apartments.com and Homes.com.' },
  WBD:  { name:'Warner Bros. Discovery',       sector:'Communications',industry:'Media · Streaming',    hq:'New York, NY',      color:'#0F0F0F', desc:'HBO, Warner Bros., CNN, Discovery, Max — 2022 merger of WarnerMedia and Discovery.' },
  FANG: { name:'Diamondback Energy',           sector:'Energy',       industry:'Oil · Gas E&P',         hq:'Midland, TX',       color:'#19324F', desc:'Permian Basin shale oil and gas producer.' },
  ON:   { name:'ON Semiconductor',             sector:'Tech',         industry:'Semiconductors',        hq:'Phoenix, AZ',       color:'#65BAEC', desc:'Power and sensing chips for automotive (especially EVs) and industrial.' },
  BIIB: { name:'Biogen',                       sector:'Healthcare',   industry:'Biotech',               hq:'Cambridge, MA',     color:'#1A1F71', desc:'Multiple sclerosis (Tecfidera) and Alzheimer\'s (Leqembi) franchises.' },
  MDB:  { name:'MongoDB',                      sector:'Tech',         industry:'Database',              hq:'New York, NY',      color:'#13AA52', desc:'Document database; Atlas managed cloud is the growth engine.' },
  GFS:  { name:'GlobalFoundries',              sector:'Tech',         industry:'Semi Foundry',          hq:'Malta, NY',         color:'#0033A0', desc:'Specialty pure-play foundry (auto, aerospace, defense, comms).' },
  DXCM: { name:'DexCom',                       sector:'Healthcare',   industry:'Med Devices',           hq:'San Diego, CA',     color:'#005EB8', desc:'Continuous glucose monitors for diabetes management.' },
  ILMN: { name:'Illumina',                     sector:'Healthcare',   industry:'Genomics',              hq:'San Diego, CA',     color:'#1F4F8B', desc:'DNA sequencers; the company most genomics labs run on.' },
  MRNA: { name:'Moderna',                      sector:'Healthcare',   industry:'Biotech',               hq:'Cambridge, MA',     color:'#D71921', desc:'mRNA-platform biotech (COVID vaccine, RSV, oncology pipeline).' }
};

export function info(ticker) {
  return COMPANIES[ticker] || {
    name: ticker, sector: '—', industry: '—', hq: '—',
    color: '#64748b', desc: 'No metadata yet for this ticker.'
  };
}
