server {
    listen 80;
    server_name _;

    root /sites/$host;
    index index.html;

    location /shared/ {
        alias /sites/shared/;
    }

    location / {
        try_files $uri $uri/ /index.html =404;
    }
}
